Feature oe sep glue 70201
dchbx/gluedb pull request #346
Opened 2020-09-20 17:21 UTC by saimekala07

2020-09-25 01:55 UTC, TreyE approved these changes
Looks correct, thanks for making fixes.

2020-10-01 00:05 UTC, TreyE requested changes
Please see my comments.  They apply likewise I believe for both 88680 and 88683.

2020-10-01 00:05 UTC, TreyE commented on app/models/external_events/enrollment_event_notification.rb
> +      return false unless existing_plan.year + 1 == pol.plan.year
Simply checking if it's for next year won't be enough.  You have to also check if the coverage would have been contiguous.  If it wouldn't have been, i.e. imagine they don't have a 2021 renewal, but a policy which begins Feb 1, 2021, we should not terminate.

2020-10-01 00:05 UTC, TreyE commented on app/models/external_events/enrollment_event_notification.rb
> +    def policies_to_cancel
Can we name the method something more like - renewal_policies_to_cancel?  I want to be able to tell that it is doing this on a renewal, and I think the method would be more descriptive of its function.

2020-10-01 23:22 UTC, TreyE approved these changes
Looks correct.

2020-10-06 13:30 UTC, TreyE approved these changes

2020-10-16 18:27 UTC, bill-transue approved these changes
Looks good, this will call `termination_cancels_renewal` for CareFirst cancellations and if it is a renewal cancellation it will call `cancel_via_hbx!` when active coverage is terminated.

2020-10-16 18:30 UTC, bill-transue approved these changes
This will silently cancel the previous carrier's auto renewal when a consumer switches carriers.

2020-10-26 19:07 UTC, merged